### ISSUE TITLE
Installing beacon-mode should install seq

### ISSUE THREAD

**Issue by asciiascetic** [Malabarba/beacon#24] opened 2015-10-27 16:17 UTC
Hello! `beacon-mode` is quite nice - I dig it.

Installing had a bit of a hiccup in that I did not already have the seq package installed.  

I installed `seq` manually, but it should be really included in `beacon-mode`'s dependencies.

Thanks again!

**Comment by Malabarba** [comment] 2015-10-27 16:37
Actually, it is in the dependencies. Did you install beacon through package.el?

**Comment by asciiascetic** [comment] 2015-10-27 17:14
Yes I did. That is odd.  It must be something in my setup. That said, failure to install listed dependencies has never happened before. I'll make a note on this thread if I discover something relevant to this project.

**Comment by Malabarba** [comment] 2015-10-27 17:19
What was the exact error message you had?

**Comment by asciiascetic** [comment] 2015-10-27 18:03
(emacs 24.5.1) After installing `beacon` via `package-install` and enabling `beacon-mode`, the `seq-find` function wasn't being found.  I looked and found that `seq` was not installed, so I installed it manually and `beacon-mode` began working as it should.  

I don't remember the exact error message, but it complained about not finding `seq-find`.

**Comment by Malabarba** [comment] 2015-10-27 23:30
It sounds like you might have had an older version of seq installed because of Melpa version numbers.

**Comment by Wilfred** [comment] 2015-10-28 00:06
FWIW, I've hit exactly the same issue. The error is:

```
beacon-blink: Symbol's function definition is void: seq-find
```

and yes, `M-x find-library seq` shows:

```lisp
;; Author: Nicolas Petton <nicolas@petton.fr>
;; Keywords: sequences
;; Package-Version: 20150709.1040
;; Version: 1.8
;; Package: seq
```

So I'm on the very latest version that's still too early!

**Comment by Malabarba** [comment] 2015-10-28 00:42
The latest seq version is 1.11 on Gelpa. 
If that's not the case on Melpa then maybe Nicolas forgot to push his changes to github. 

In any case, I strongly recommend people delete dependency libs installed from Melpa and install them from Melpa-stable or Gelpa instead.

**Comment by Malabarba** [comment] 2015-10-28 06:37
I've seen this happen to 3 people already only on this package. Pinging @nicolaspetton just in case he's not aware that this happens.

**Comment by NicolasPetton** [comment] 2015-10-28 08:50
I'm not, I haven't faced this issue myself. Is it reproductible?

**Comment by Malabarba** [comment] 2015-10-28 09:08
It's hard to reproduce. It happens when:

- A user installed `seq` (either manually or by dependency) from Melpa a while ago.
- The user later installs some package that depends on a newer vesion of `seq`.
- The newer version of `seq` will not be installed because Melpa version number are gigantic, so the old version will be thought to already satisfy the new dependency.

This is why it's best to not add such libs to Melpa if it can be avoided (user packages are fine, but packages that serve as dependency libs suffer a lot from this).

It's hard to reproduce because Melpa doesn't keep old package versions. But you can sort of trigger manually by:

1. Check out a really old version of `seq.el`.
2. Change its version number to `20150000` (a typical Melpa version number).
3. `M-x package-install-from-buffer` on it.
4. Then go to `list-packages` and try to install a package that depends on a newer version of `seq`. The package will be installed but seq won't be upgraded.

One ugly workaround some people use would be to bump seq.el's version number to be higher than those that Melpa uses.

**Comment by NicolasPetton** [comment] 2015-10-28 09:16
Thanks for the explanation.  I don't think there's much to be done about this at this point though (removing `seq` from MELPA entirely?), but the issue should disappear with time.

**Comment by tollerm** [comment] 2015-10-30 20:08
Hi, 
I have the similar issue with the seq library. My error message is : (void-function seq-mapn). I am using the last version of Emacs 25 from the Github repository with seq library version 2.1 which does not have this function. As I can see, this function was added to seq library 2 days ago but still is not present in the last Emacs build.
Best regards, Toller

**Comment by Malabarba** [comment] 2015-10-30 20:36
@tollerm this function has been added to emacs master. Maybe the github repository you're pulling from isn't up to date. 
Try using the source repo instead.

**Closed** 2015-10-31 06:32 UTC
