### ISSUE TITLE
Beacon mode does not work with evil mode page up and down

### ISSUE THREAD

**Issue by KulkarniKaustubh** [Malabarba/beacon#81] opened 2022-03-02 20:20 UTC
Emacs: 27.1

I use evil mode and when I use C-d or C-u to page down or page up, the beacon does not blink. It however, does blink when I switch over to emacs state from evil state and use C-v and M-v for page up and down.

Do I need to add something to my beacon config?

**Comment by AutumnalAntlers** [comment] 2022-06-01 04:37
`evil-scroll-up` calls `(next-line n)`, which is excluded by default as a member of the list `beacon-dont-blink-commands`: "predictable commands which would be more distracting than helpful".  

To make this work quickly you could add `(setq beacon-dont-blink-commands '(previous-line forward-line))`, and to work around this just for evil you could advise the functions like so:
```
(defun beacon-do-blink-command (func)
  (advice-add func
    :around
    (lambda (func &rest args)
       (let ((beacon-dont-blink-commands '()))
        (apply func args)
        (beacon--post-command)))))
(mapc #'beacon-do-blink-command
      '(evil-scroll-up evil-scroll-down
        evil-goto-first-line evil-goto-line)))
```

**Comment by Malabarba** [comment] 2022-06-01 17:00
Thanks for figuring out the reason @AutumnalAntlers.

Do you have the code for those evil-scroll-x functions? It seems odd that things would interact this way... :thinking:

**Comment by Malabarba** [comment] 2022-06-02 01:50
Ooooh, I see. 
Well, then you're definitely right, that's the cause.
I would suggest submitting a bug report to evil, but if they did something so specific, they probably had their reasons. :-)

Anyway, closing this issue here. Thanks for the help @AutumnalAntlers

**Closed by Malabarba** 2022-06-02 01:50 UTC
